[profile.default]
src = "src"
out = "artifacts"
libs = ["lib"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
]
solc_version = "0.8.15"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
